### ISSUE TITLE
Compatibility with FFZ

### ISSUE THREAD

**Issue by Dgc2002** [kwaschny/unwanted-twitch#1]
It appears that this project has some issues working alongside [FrankerFaceZ](https://github.com/FrankerFaceZ/FrankerFaceZ).  
  
When either FFZ or this extension are enabled without the other I can load the main directory just fine. But when they're enabled together all of the streams disappear. Here's a recording:    

![2018-08-25_15-44-52](https://user-images.githubusercontent.com/3957791/44622497-1fa4b100-a87f-11e8-8068-d381e93c6b5b.gif)

Here's the relevant log/error section: [www.twitch.tv-1535230504526.log](https://github.com/kwaschny/unwanted-twitch/files/2321040/www.twitch.tv-1535230504526.log)

**Comment by ctroller** [comment]
Can confirm that this is happening with BTTV as well with the same log message.

**Comment by kwaschny** [comment]
It's a race condition where FFZ attempts to reference a node that is being removed by UnwantedTwitch. This can be solved by not removing nodes but hiding them so other extensions can still reference them. My first fix attempt does seem to work, but needs more testing.

I never tested with FFZ so far. There might be even more issues.

**Comment by kwaschny** [comment]
Nodes will no longer be removed from DOM, instead they will be hidden (using CSS). I also had to disable the scroll trigger since FFZ seems to have an issue with that. Changes in: 44ef2196988694491a8e109b31cf7fbade571758

The fix is part of update version `18.8.30`.

**Comment by dclar43** [comment]
Working for me! Thanks. Now I can finally move away from using forks of the old "hide unwanted streams on twitch" script.
