### ISSUE TITLE
Hid channel when it shouldn't have

### ISSUE THREAD

**Issue by Splertiki** [kwaschny/unwanted-twitch#100]
Liriks channel was hidden with title of only "?"

![image](https://user-images.githubusercontent.com/92955090/204154210-4f2bdeef-1b96-4f39-bbbc-bfbf5ff182db.png)
![image](https://user-images.githubusercontent.com/92955090/204154252-4f0f96fa-a9f3-42bc-86b4-0094e015e94d.png)
![image](https://user-images.githubusercontent.com/92955090/204154220-d21d9abe-5a82-4cec-a624-66540841189d.png)

**Comment by kwaschny** [comment]
This might be related to [this current issue on twitch's end](https://www.reddit.com/r/LivestreamFail/comments/z77294/twitch_not_showing_asmongold_in_the_discovery/). Multiple people have reported this, especially for LIRIK and Asmongold.

I have the same issue, even without UTTV. Not a bug to fix on my end.
