### ISSUE TITLE
Filter by channel name  (add regex to channel name filter)

### ISSUE THREAD

**Issue by OpenSourceCon** [kwaschny/unwanted-twitch#101]
Hi Alex,
Thank you so much for your work on this extension, it's great!

I am wondering if it is possible to filter channel names like it is currently possible for titles. As in use regex to filter certain words from channel name rather than having to go through and block individual channels using the 'X' button. e.g in the music category, block all channels starting with 'dj' or containing 'radio'. 

I had tried using the /^live/ regex in the extension itself but it seems this is not possible currently?

Thank you!

**Comment by kwaschny** [comment]
Hi, this feature has already been suggested in #31.

**Comment by OpenSourceCon** [comment]
Apologies, missed that one. Thanks again.
