### ISSUE TITLE
Add timestamp/ability to sort by when added to blacklist

### ISSUE THREAD

**Issue by PsychoSek** [kwaschny/unwanted-twitch#103]
I've had a few instances, where I've accidentally clicked the X to block a channel.

Depending on what I'm browsing through and considering how many channels I've blacklisted, I have effectively no way to find that channel and unblock them.

Is there a way to do this that I'm not aware of, and if not, could one be added? Perhaps a timestamp added along with the blacklisted item that could potentially be sorted to see your latest additions and such. Thank you!

Love the extension though! Great work!

**Comment by kwaschny** [comment]
Extension storage limits are already very tight (5 MB `local`, 1 MB `sync`), so there is no way I'm "wasting" even more bytes for a timestamp (that needs to be stored as JSON) per item.

I'll add `unlimitedStorage` permission (for `storage.local`) once I have to update to the new manifest version around mid-year.

Someday™ I might rewrite the whole storage to `IndexedDB` and won't have to worry about storage size at all.
