### ISSUE TITLE
Empty space where filtered user(s) are on "Following" page.

### ISSUE THREAD

**Issue by usernameisunavailableisavailable** [kwaschny/unwanted-twitch#104]
Using Chrome (I have not experimented with other browsers), instead of the filtered user being filtered from the "following" page, there is an empty space where filtered users are intended to be.

Are there plans to alter Unwanted Twitch so that there is no empty space where the filtered user would have been on the following page?

**Comment by kwaschny** [comment]
Yup, something changed, can confirm. I'll look into it.
