### ISSUE TITLE
Seems like there is a limit to the block ammount.

### ISSUE THREAD

**Issue by HolySoap** [kwaschny/unwanted-twitch#105]
I had blocked 50+ categories, 320+ channels (not 100% sure about the amount could have been over 350+, because of *down below*) and 140 tags.
With so many blocked the addon couldn't take more entries, not even adding them manually. Every attempt to add more resulted in Firefox giving an error about Twitch when Twitch was open and not adding it to the list.

By clearing the channel list the addon is able to add new entries again.

**Comment by kwaschny** [comment]
> Every attempt to add more resulted in Firefox giving an error about Twitch

What exactly did it say? Any console errors?

**Comment by HolySoap** [comment]
> > Every attempt to add more resulted in Firefox giving an error about Twitch
> 
> What exactly did it say? Any console errors? Also, are you using the cloud sync or local storage mode (see top-right in extension settings)?

Cloud sync is on.
Just to answer your question I blocked as much as possible to get the error again. After I get that error 3 or 4 times on the same page it changes a little and a checkbox appears that lets me silence it for that exact page.
![Screenshot_2023-04-21_07:45:43](https://user-images.githubusercontent.com/65773051/233550984-aff15a7a-4915-437f-9dbf-c0239967111c.png)
![Screenshot_2023-04-21_07:49:35](https://user-images.githubusercontent.com/65773051/233551002-d644dc80-818c-46ad-bc90-e12c683965e2.png)

**Comment by kwaschny** [comment]
That's a fallback response to the [storage.sync.set() callback](https://github.com/kwaschny/unwanted-twitch/blob/1d25793af1ae7a9d211ddb1bc4bf1819bf1ce798/scripts/directory.js#L2486) in case `runtime.lastError` has been set by Firefox. **This is not related to the extension but the cloud storage service that Firefox uses to sync your data.** I do not expose the exact reason in the dialog, but it's certainly not related to storage quota. Maybe you are no longer authenticated with your Firefox profile?

I recommend going without cloud sync in this case. The local storage mode is more reliable and also able to store way more data. Make sure to do a backup/export regularly anyway.

**Comment by HolySoap** [comment]
Everything is good with my FF account, but that's something I've notice for a long time now, the data that the add-ons have themself don't get synced. A good example is uBlock, no settings are synced, not even with uBlocks own version, it gets uploaded but never downloaded on another device.

Anyway, glad to hear that it isnt an error and has an easy solution.
Thank you and have a nice day!
