### ISSUE TITLE
Blocking Script types

### ISSUE THREAD

**Issue by Way2Bad** [kwaschny/unwanted-twitch#106]
It would be cool if we could block tags that include scripts like cyrillic, korean, chinese etc, streamers don't tag which language they speak in but having such tags almost always mean they stick to their own language.

**Comment by kwaschny** [comment]
With the most recent version\* of the extension (23.5.3), you can use **regular expression for tag filtering**. You can then specify the unicode character range you want to block.

`/[\u0400-\u04FF]/` would hide items that have tags with any characters from the cyrillic alphabet.  
`/[\u1100-\u11FF\u3130-\u318F\uA960-\uA97F\uAC00-\uD7AF\uD7B0-\uD7FF]/` for hangul.
etc.

\* *The update for Firefox and Edge are still in review at this point in time. So those will take a few more days.*

**Comment by Way2Bad** [comment]
Yeah was about to suggest including regex instead you beat me to it.
