### ISSUE TITLE
No longer saves changes (Brave browser)

### ISSUE THREAD

**Issue by Taomyn** [kwaschny/unwanted-twitch#112]
Using the Chrome version on Brave, extension was doing it's job but discovered today changes are no longer saved.

Tried the suggested export/import, no difference, removed/readded extension and import, still the same. Have lost all the settings now apart from the export that no longer imports.

**Comment by kwaschny** [comment]
The broken save bug has been reported multiple times now. I assume it is a race condition due to a loose callback somewhere. I prepared a proper async/await refactoring to fix this. Said bugfix will be released soon.

**Comment by kwaschny** [comment]
I assume this is resolved now.
