### ISSUE TITLE
Block categories like "Let's Get Creative"

### ISSUE THREAD

**Issue by AidenJames1995** [kwaschny/unwanted-twitch#113]
Is there any mechanism to block suggested channels on the homepage that aren't technically categories such as "Let's Get Creative" (https://www.twitch.tv/directory/collection/creative) or "Verified Charity Streams" (https://www.twitch.tv/directory/collection/verified-charity)? I tried manually adding them to Blacklisted Categories but doing so doesn't effect anything.

**Comment by kwaschny** [comment]
Blacklisting always requires context. As long as these "collections" are not part of each channel item, they cannot be blocked. So unfortunately, that's a nope.
