### ISSUE TITLE
How do i Block GTA?

### ISSUE THREAD

**Issue by MonfGeiger** [kwaschny/unwanted-twitch#116]
So im trying to use this extension (awesome as it is) to block grand theft auto V from showing up in my vtuber twitch results (because i frankly don't care for GTA nowadays), and seemingly no matter how i parse it, whether i add `grand-theft-auto-v` to the category block section or any derivative, it still shows up in twitch results

just in-case im doing it wrong, can someone please help this scrub and tell me if this extension can indeed block GTA V from showing up in any twitch results, and if so wat do?

**Comment by kwaschny** [comment]
`grand theft auto v` to block 5 or `~grand theft auto` to block all of them. Where (path in address bar) does it still appear for you? Maybe that view is not supported by the extension?

**Comment by MonfGeiger** [comment]
.......i wish i realized that earlier. My bad, i am sorry for retroactively wasting an issue tab, my apologizes

i accept the dunce hat
