### ISSUE TITLE
Blacklist changes doesn't save

### ISSUE THREAD

**Issue by RikisX** [kwaschny/unwanted-twitch#118]
No changes to blacklist are saved with version 23.10.17. Version 23.6.10 works fine.

Firefox 115.6.0esr 64-bit. 
Windows 11.

**Comment by kwaschny** [comment]
How do you save to the blacklist? Using the `X` button or manually entering and saving? Please try to provide relevant console information. Also read [Report bugs](https://github.com/kwaschny/unwanted-twitch/blob/master/CONTRIBUTING.md).

**Comment by RikisX** [comment]
Clicking "Save" button.

**Comment by kwaschny** [comment]
Closing this as no additional information have been provided.
