### ISSUE TITLE
BUG: Nothing is being blacklisted

### ISSUE THREAD

**Issue by Ragowit** [kwaschny/unwanted-twitch#126]
I just downloaded this to try it out, but even after I have added several names into the "title" category so is nothing being blacklisted. Haven't tried the other categories.

EDIT:
- What browser and what version of it are you using?
Google Chrome, Version 130.0.6723.59 (Official Build) (64-bit)

- What version of Unwanted Twitch are you using?
24.3.30

- Are you using other extensions that might affect the Twitch website?
No.

- Does disabling all the other extensions (except Unwanted Twitch) help with the problem?
No.

- What are the steps to reproduce the problem?
1. Install Unwanted Twitch
2. Add "rerun" to the Blacklisted Titles section, then press Add.
3. Check "Hide Stream Reruns" option.
4. Press Save.

- If applicable: Can you show a screenshot of the issue?
![image](https://github.com/user-attachments/assets/cd06102b-5556-4dec-9445-8bb9b76630fd)
![image](https://github.com/user-attachments/assets/d5901f29-faa0-418e-b96a-9993920ac1bd)

- If applicable: Can you share the export of your blacklist?
[UnwantedTwitch_Blacklist.json](https://github.com/user-attachments/files/17470799/UnwantedTwitch_Blacklist.json)

- Advanced users: Share the console messages and stacktrace.
![image](https://github.com/user-attachments/assets/80c58cfe-efb4-4568-a8a5-a75cbc7e396e)

**Comment by kwaschny** [comment]
Please read the instructions on [how to report bugs](https://github.com/kwaschny/unwanted-twitch/blob/32983861bbfb7ed9426a6a7f58cbdc0d6b091ee4/CONTRIBUTING.md#report-bugs) and also check out the [FAQ / Troubleshooting section](https://github.com/kwaschny/unwanted-twitch?tab=readme-ov-file#faq--troubleshooting). It's impossible to know what is happening on your end without you providing sufficient information.

**Comment by Ragowit** [comment]
Updated original post with more information as per [how to report bugs](https://github.com/kwaschny/unwanted-twitch/blob/32983861bbfb7ed9426a6a7f58cbdc0d6b091ee4/CONTRIBUTING.md#report-bugs).

**Comment by kwaschny** [comment]
If you click on "Supported patterns explained..." (found beneath the input in each column), you will see the rules for adding terms manually. In your case, you want to add it as `~rerun` (note the tilde `~` in front) to make the word "rerun" match anywhere in the title. Your current term `rerun` requires the whole title to only consist of "rerun", which is not the case for any of the circled items in your screenshot.

Also note that the checkbox for `Hide Stream Reruns` refers to the official rerun flag. If you can see a red "LIVE" marker on the stream tile, these channels are technically live and just happen to play a pre-recorded video. People have been doing this for a long time. I guess one could argue that blocking streams with "rerun" in the title should be part of the checkbox.

**Comment by Ragowit** [comment]
Ah, I understand. I assumed the default behavior was to match a word anywhere. Since I can hardly see the use case of a time when someone wants to exclude an exact title match.

Can you bump up the explanation of "~half-life" to be on top? I suspect this is the scenario 99.999% of the users wants to use.

![image](https://github.com/user-attachments/assets/7dece174-7f89-40ec-9dc0-95cbf7b54d69)
