### ISSUE TITLE
doesn't work with new firefox update

### ISSUE THREAD

**Issue by imphilxd** [kwaschny/unwanted-twitch#13]
Doesn't work with newest firefox version 65.0
To be expected I guess, could always revert the ff update. Just thought I'd let you know though.

**Comment by imphilxd** [comment]
nevermind, it works.

**Comment by imphilxd** [comment]
nevermind, it works.

**Comment by kwaschny** [comment]
Hm, I wonder if Twitch is partially rolling out new layouts again, because it works perfectly fine on FF 65 for me. Do you notice any changes, like new elements in the view?

**Comment by kwaschny** [comment]
I've released a new version with some bugfixes. Maybe that resolves your issue. If that still doesn't help, feel free to reopen the issue.
