### ISSUE TITLE
[Feature Request] Hide broadcasts with certain keywords

### ISSUE THREAD

**Issue by phillipwei** [kwaschny/unwanted-twitch#14]
Certain channels I follow will broadcast a rerun but put the word "RERUN" in their title, without actually having it tagged/listed as such. I would love to be able to filter these out.

Having this be a wildcard expression/regex would be a more generalized solution.

**Comment by phillipwei** [comment]
By the way, I am a developer and very happy to make the change and issue a PR -- however, I don't see a contribution guide in this repo so don't want to misstep or cause you any problems. I know many solo maintainers prefer to do the coding themselves, but I'm just as happy to write the code. Let me know what you prefer.

**Comment by kwaschny** [comment]
Sure, you can work on it and make a PR. I'll check it and adjust it, if necessary. Contrbution guidelines seem a bit overkill for this small project.

> Having this be a wildcard expression/regex would be a more generalized solution.

If you are talking about a general regex filter to hide any channel that matches: hell no. Many users are already confused by how the whole thing works. Having some sort of "advanced settings" would kill the rest of the intended simplicity.

But I guess you meant a regex to catch stream re-runs like `\bre[^a-z]?run`, that's fine of course.

**Comment by kwaschny** [comment]
Closed as of now. There doesn't seem to be a big interest anymore and this feature would just make the settings area even more cluttered.
