### ISSUE TITLE
Request: Hide all channels titled "Untitled Broadcast", and/or with category "Not specified"

### ISSUE THREAD

**Issue by habibe36** [kwaschny/unwanted-twitch#19]
Is this a reasonable/achievable feature? The channels listing often features numerous obviously infringing sports broadcasts, made with dummy accounts and almost always without titles or categories set. All real channels seem to set at least one or the other. These get banned but of course pop right back up with a different channel name. I couldn't find a way to hide these across the board with the base features. Thoughts?

**Comment by kwaschny** [comment]
From a technical point of view, it's feasible. In fact, hiding channels based on keywords in the title was already suggested back in #14.

But I'm still not sure if it's worth being implemented. While your use case sounds reasonable, it also sounds kinda niche. Are you sorting channels from lowest to highest viewers?

I'm open to opinions here.

**Comment by habibe36** [comment]
Just the default channel view (sorting high to low). Maybe it's just the times of day I tend to use it (I'm UTC -6), but it's quite common for me to see 4-5 streams in the 2-5 thousand viewer range, with a couple more popping up every time I scroll down. If a big team is playing it seems to just get flooded. I use the default channel view as my homepage, but I don't know how common that it.

**Comment by Xiaminou** [comment]
![Image](https://i.imgur.com/eaGKC5d.png)

**Comment by kwaschny** [comment]
Implemented with 4a402e6ebeb163e6cc4ccba4f8ea804aeaceb4d1.
