### ISSUE TITLE
New permission: "Read your browsing history"

### ISSUE THREAD

**Issue by Dgc2002** [kwaschny/unwanted-twitch#2]
I was just notified that this extension needed permission to read my browsing history, which kind of crosses a line IMO.  
  
I see you added `tabs` as a permission in 52dd39ec which is what triggered it(had to check the [permission warnings list](https://developer.chrome.com/apps/permission_warnings) to figure out that was the cause).  
  
IMO it'd be best to avoid that kind of thing as it will cause a lot of privacy minded people to remove the extension.

**Comment by kwaschny** [comment]
Sorry, that was unintended. The "tabs" permission is required for Firefox to get all twitch.tv tabs. However, Chrome doesn't need this permission and shows a warning. I just removed the permission in the Chrome manifest, see: 7c7484917766956569438d2cf7e37ad0ba3d374b

**Comment by kwaschny** [comment]
I also adjusted the Firefox part to not require the "tabs" permission. I can see why people think it's fishy. Let's not change any permission without double checking it ever again. _FeelsBadMan_
