### ISSUE TITLE
Donation

### ISSUE THREAD

**Issue by xRudeAwakening** [kwaschny/unwanted-twitch#20]
Is there somewhere I can donate to the creator(s) of this? This has seriously changed twitch for me.

**Comment by kwaschny** [comment]
You can donate [via PayPal](https://www.paypal.me/devservice) or [buy me a coffee](https://www.buymeacoffee.com/devservice). There also links on [the Firefox Add-on store page](https://addons.mozilla.org/de/firefox/addon/unwanted-twitch/) and on [my personal homepage](https://kwaschny.net/). Donations are appreciated but kept anonymous.
