### ISSUE TITLE
Sidebar not filtered while on actual stream.

### ISSUE THREAD

**Issue by Fyren** [kwaschny/unwanted-twitch#21]
Based on the readme's "supported pages" section and `getItemType()`/`isSupportedPage()`/`onPageChange()`, it seems like there's intentionally no filtering going on when on an actual stream's page even though the sidebar is visible.  Is there a problem with filtering the sidebar on other pages?

I tried calling `filterSidebar()` and `observeSidebar()` in the case where it bails out early in `onPageChange()` just to very quickly test and it appears to work and not cause problems.

**Comment by kwaschny** [comment]
Correct, I intentionally don't tinker with the stream page because that's where the other popular add-ons (FFZ/BTTV) do lots of DOM manipulation (e.g. chat area). I don't think it's worth to invoke UTTV on busy pages like this one.

**Comment by Fyren** [comment]
Would you accept a PR to add a checkbox, defaulted to off, to turn on sidebar filtering on Twitch pages not currently supported?

**Comment by kwaschny** [comment]
Sure.

**Comment by kwaschny** [comment]
Feel free to reopen if you decide to work on it.

**Comment by kwaschny** [comment]
I reconsidered due to popular demand. I'll be adding sidebar filtering to the stream view.
