### ISSUE TITLE
New Twitch Layout

### ISSUE THREAD

**Issue by kwaschny** [kwaschny/unwanted-twitch#22]
Extension pages on Chrome Web Store and Firefox Add-ons are disabled for now. I need some time to check the changes Twitch made to the new layout. Let's see if adjusting the selectors is good enough. Anyway, I'll need some time to work on that.

**Comment by sKippah** [comment]
Happy to see ur still supporting it. Thanks a lot

**Comment by kwaschny** [comment]
Almost done. Only the new "Following" pages and some more testing remaining.

**Comment by kwaschny** [comment]
All changes done in 8262056e290959628834dea90a6af29e403f2fe9. Update is on its way. Extension pages should be up again.

**Comment by sKippah** [comment]
Hi. First of all, I would like to "say" thank you for your work.
Blocked channels no longer appear in the "Recommended Live Channels" list, but they leave an empty space in the live channels list (See Attachement)

Would an additional function be possible to block streams directly in the "carousel" and in the "Recommended Live Channels" list?


![Twitch Screen](https://user-images.githubusercontent.com/5049659/66189139-57d51080-e689-11e9-9f5d-b6b4118fd234.png)
