### ISSUE TITLE
Only first row allows me to block categories

### ISSUE THREAD

**Issue by Nachot93** [kwaschny/unwanted-twitch#24]
With the recent update I got the block function back, but only works for the first row. See image.

![image](https://user-images.githubusercontent.com/15396315/66482939-6ef57300-ea7a-11e9-8235-65a06dc785f3.png)

**Comment by alxthaman** [comment]
Can confirm, same thing for me since yesterday.
Channel blocking is unaffected though.

Thank you for that great add-on!
