### ISSUE TITLE
Add Alternative way to toggle "hide" buttons 

### ISSUE THREAD

**Issue by BubiBalboa** [kwaschny/unwanted-twitch#26]
Hi! Love the add-on!

I'm not a huge fan of page-action buttons even when they make sense for add-ons like yours which is only active on one domain. I usually just remove them. 

Problem is there is not alternative way to toggle the "hide" buttons. It would be cool if you could add the option to show a toggle in the header bar of the Twitch page itself. Or just have a classic add-on button act as a toggle which we can hide in the overflow menu until it is needed.

Thanks!

**Comment by kwaschny** [comment]
You can remove the page-action button from the address bar and just access it via "..." whenever you want to toggle the "Show X Buttons". Doesn't that solve your problem?

![Demo](https://user-images.githubusercontent.com/35005943/67628087-51891d00-f860-11e9-99b6-6fd252e63d9f.gif)

**Comment by BubiBalboa** [comment]
Thanks for reminding me of that option. I have hidden the three dot menu in my userChrome.css that's why I didn't think of it. 

I still think the option to display a normal extension button would be nice just to be more flexible with your setup. 

It's not super critical but maybe a nice thing to add in the future.

**Comment by kwaschny** [comment]
Added fastswitch to toggle "X" button visiblity to the management button:
![image](https://user-images.githubusercontent.com/35005943/73794972-ce099100-47a9-11ea-9883-ff7b628c9281.png)
