### ISSUE TITLE
Twitch site update broke the plugin

### ISSUE THREAD

**Issue by Hennricko** [kwaschny/unwanted-twitch#29]
As the title says, plugin broke a couple hours ago with a Twitch site update. The plugin currently doesn't hide anything that is already blacklisted (as far as I can tell), and clicking on the X on any stream causes an empty/blank entry to be added to the "blacklisted channels" list, which then causes every single streamer to be filtered out endlessly till that broken entry is removed or the plugin is disabled.

Browser is Vivaldi 2.11.1811.33 (yet another chrome clone basically)
Not using any other plugins affecting twitch, but apparently betterttv also broke.

![emptyentry](https://user-images.githubusercontent.com/44590626/76270755-9c875800-6276-11ea-8dd0-ee79432d8693.png)

**Comment by Zenzou** [comment]
Not working on Firefox either. If it helps, here are the console errors I'm getting.
![twitchblockerror](https://user-images.githubusercontent.com/7418181/76350499-1cd6a900-62c9-11ea-8bbc-8b6835f3b26d.png)
