### ISSUE TITLE
Allow regex to be used on Blacklisted Channels

### ISSUE THREAD

**Issue by spencebal** [kwaschny/unwanted-twitch#31]
Allowing regex to be used on channels will help filter out the bots that re-stream for popular users.

Example below is a list of bot channels I have had to blacklist so that they do not appear at the top of popular stream categories. Regular expressions could easily filter out these examples instead of adding each one individually.

shroudbkep 
shroudcdh 
shroudexbq 
shroudfqbl 
shroudied
shroudkta
shroudlisx
shroudlob
shroudlqv
shroudltdu
shroudmahs
shroudmjpp
shroudnjaj
shroudov
shroudryk
shroudtmwe
shroudtvfv
shroudtynv
shrouduazl
shroudysvz

**Comment by kwaschny** [comment]
You can already do this in the management view. Check the 4th column. There are instructions available how to add specific patterns. In your case that would be: `/^shroud.+/`
![image](https://user-images.githubusercontent.com/35005943/77686806-c5f5f280-6f9d-11ea-9b63-24d86fe3b733.png)

**Comment by spencebal** [comment]
Thank you, it wasn't clear that it was available for each column since the pattern explanation was only on the 4th column.

**Comment by kwaschny** [comment]
Oh wait, no, that's not implemented.

**Comment by testdev123456** [comment]
I would love this feature!! so many bots these days!!!

**Comment by kwaschny** [comment]
Feature added with 69e25e6545d81e205ef75aabfa5b23156d1d69bf. Update still pending though.
