### ISSUE TITLE
tiny cross to block channel from thumbnail has disappeared

### ISSUE THREAD

**Issue by Kiewan** [kwaschny/unwanted-twitch#32]
Hello,

Since a few days the tiny cross on the upper right side has disappeared to block channel. How can I turn it back on again?

![image](https://user-images.githubusercontent.com/63482707/79032289-95b97100-7ba5-11ea-9a2c-e85abeef603a.png)

**Comment by kwaschny** [comment]
Click on the eye symbol next to the manage button that should appear top right on the directory pages.

![image](https://user-images.githubusercontent.com/35005943/79032671-9f90a380-7ba8-11ea-8010-521cdf91342c.png)

Another option is using the extension's popup in the top right corner of your browser. Toggle the checkbox there for the same effect.

![image](https://user-images.githubusercontent.com/35005943/79032707-e4b4d580-7ba8-11ea-99a2-6dc3edeabeae.png)

If you cannot see the extension icon here, click on the 3 dots and select the icon at the top.

(Screenshots show the German localization.)

**Comment by Kiewan** [comment]
Thanks, it worked!
