### ISSUE TITLE
Inverse method of blocking possible?

### ISSUE THREAD

**Issue by d4nl** [kwaschny/unwanted-twitch#34]
The current implementation allows everything but what is blocked by the user.

Is it possible to do the inverse? That is block everything but what is allowed?

For example block all channels but those with the "English" tag

**Comment by kwaschny** [comment]
The extension applies its filters after twitch.tv served the request, so blacklisting is the only reasonable functionality. If you want to whitelist, use the already available filters on twitch.tv by clicking/searching tags.

![image](https://user-images.githubusercontent.com/35005943/80282218-88a59180-8710-11ea-84f6-dd2e246fea7b.png)
