### ISSUE TITLE
Twitch won't load while it is enabled

### ISSUE THREAD

**Issue by RooTeeM** [kwaschny/unwanted-twitch#35]
Hello, after using the add-on, the Twitch.tv website would no longer load. And I would need to disable it for it to work.

**Comment by kwaschny** [comment]
- What browser and what version are you using?
- Are you using other extensions that affect the Twitch website?
- Does disabling all the other extensions (except Unwanted Twitch) help with the problem?
- What are the steps to reproduce the problem?
- Can you show a screenshot of the issue?
- Can you share the export of your blacklist?

**Comment by RooTeeM** [comment]
Firefox 76
Bettertv and FrankerFacez
Sadly no
Enabling the addon then closing firefox and reopen it again

[url=https://postimg.cc/gw4qbpx0][img]https://i.postimg.cc/gw4qbpx0/Annotation-2020-05-06-171343-PNG.jpg[/img][/url]

[url=https://postimg.cc/8J5d1Yvm][img]https://i.postimg.cc/8J5d1Yvm/Annotation-2020-05-06-171403.jpg[/img][/url]

https://ufile.io/qrxs4b1n

Thank you for your time

**Comment by kwaschny** [comment]
Not able to reproduce it. Does the twitch.tv page stay blank/white? Does it keep saying "Trasferring data from ..." in the bottom status bar?

Can you share Firefox' console ouput? Press `F12` to open the developer toolbar. Then switch to "Console" (if not already selected) and copy/paste the output here. If you keep getting "Transferring data from ...", you might also want to check the "Network" tab for long running or stalled requests. Note that this requires you to open the developer toolbar before visiting twitch.tv.

**Comment by RooTeeM** [comment]
From what I understand, if twitch is open, even in another window I can enable it and even close the current window with no issues, But as soon as I close everything, it won't open.

https://i.postimg.cc/C5PJMdp0/Annotation-2020-05-06-205446.jpg
https://i.postimg.cc/nV03GSjW/Annotation-2020-05-06-211043.jpg

**Comment by kwaschny** [comment]
The extension doesn't load any external libraries that would require HTTP requests, so a network interference on the extension's side is unlikely. Maybe there's corrupt data in cache. **Try clearing your cache, cookies and storage and see if that helps.** Other than that, I unfortunately cannot help you any further as the extension is not even picked up before the twitch.tv page loads, which is exactly the case here. :(

**Comment by RooTeeM** [comment]
Unfortunately doing that did not help. I appreciate the time and the effort.
