### ISSUE TITLE
Blacklisting categories on their Twitch page does not add them to blacklist; Chrome 81.0.044

### ISSUE THREAD

**Issue by Pendji** [kwaschny/unwanted-twitch#36]
Think I've had this issue since I installed it months ago. Adding categories to the blacklist itself does work, so does the streamer tags (English, WR Attempts etc). 

I have to manually add the game names to the blacklist, upon which doing reveals that the blocked game sections are never added thereto, regardless of whether it says so on their respective pages.

**Comment by kwaschny** [comment]
You mean adding it via input in the management view works, but clicking on the X button does not? Your description is a bit confusing, to be honest. Can you elaborate please?

Also please answer the [common troubleshooting questions](https://github.com/kwaschny/unwanted-twitch/blob/master/CONTRIBUTING.md):
- Are you using other extensions that affect the Twitch website?
- Does disabling all the other extensions (except Unwanted Twitch) help with the problem?
- What are the steps to reproduce the problem?

**Comment by Pendji** [comment]
Hi, sorry for the lack of information.

- I'm using FrankerFaceZ though as far as I'm aware, it has no functions outside the chat.

- Disabling Unwanted Twitch removes the blacklist function entirely, so I can't really test without it.

- Click onto any specific game page, such as (https://www.twitch.tv/directory/game/Counter-Strike%3A%20Global%20Offensive) and click the 'Block' bottom under the game name in the top. It will change to 'Unblock', implying the game is blocked from appearing, yet it still appears. Opening the 'Manage blacklist' button on the right side of the same page shows all the blacklisted tags, that do function properly, but it does not include the game that was just blocked unless added manually, in which case it then functions normally and removes the game from the stream browser.

**Comment by kwaschny** [comment]
The "Block" button on the category page is from FrankerFaceZ and is not related to the blacklist from UnwantedTwitch:

![image](https://user-images.githubusercontent.com/35005943/83254850-a783c180-a1af-11ea-82b7-f51a58bb2ad1.png)

For UnwantedTwitch to work, you need to block a category/game via the "X" button (on the "Browse" page):

![image](https://user-images.githubusercontent.com/35005943/83255173-3e507e00-a1b0-11ea-847b-c042b3ff890b.png)

or enter it manually in the management view. :)
