### ISSUE TITLE
Blacklist not working again

### ISSUE THREAD

**Issue by Zenzou** [kwaschny/unwanted-twitch#37]
Browser is Firefox 76.0.1 and addon version is 20.3.22.
Channels on blacklist are showing up again.

**Comment by kwaschny** [comment]
Yup, looks like the June update. All items are affected.

**Comment by kwaschny** [comment]
For some reason I no longer see changes and everything is working again. Maybe Twitch is rolling out/back experimental stuff in multiple waves? Either way, I cannot fix what is not broken yet.

**Comment by Squachen** [comment]
For me it seems to only be broken for the "Recommended channels" part on the following-page since the new (awful) twitch layout.

Firefox 77.0
Addon version: 20.3.22

**Comment by patti2** [comment]
Can confirm, "Recommended channels" section isn't being filtered.
Firefox 78.0b3

**Comment by garethhubball** [comment]
Can confirm the same as @patti2 
Chrome 83.0.4103.97

**Comment by kwaschny** [comment]
Frontpage and Following broken.
