### ISSUE TITLE
Chromium Edge

### ISSUE THREAD

**Issue by Darktowertr** [kwaschny/unwanted-twitch#38]
Could you take the extension to the Chromium edge extension store?
https://microsoftedge.microsoft.com/addons/Microsoft-Edge-Extensions-Home

**Comment by kwaschny** [comment]
I just submitted the Chrome version to the Microsoft Edge-Add-Ons. It's in review now.

As a side note: You can use any Chrome extension on Chromium based Edge anyway. Just go to `edge://extensions/` and there you see an option to enable it and a link to the Chrome Web Store. 🙂

**Comment by kwaschny** [comment]
https://microsoftedge.microsoft.com/addons/detail/unwanted-twitch/jkhpefiopamdlihbichhnhmpfgomefmh
