### ISSUE TITLE
Settings don't save

### ISSUE THREAD

**Issue by azizLIGHT** [kwaschny/unwanted-twitch#39]
When I added a category or channel into the options and hit add and click save and then reload the options page, whatever I added disappears.

Chromium 83.0.4103.61

**Comment by kwaschny** [comment]
If you add an entry manually in the management view, the tab should close automatically after pressing the Save button. Does that happen?

Did you try switching from cloud to local storage (top right option)?

How many other tabs are opened when you test? Try it with just a single tab (and no additional windows).

**Comment by azizLIGHT** [comment]
I'm not sure what happened but after closing all my tabs/windows and uninstalling/reinstalling the extension and then testing with just 1 twitch tab and 1 extension management view tab it started working and saving whatever I added/removed. Then I opened up all my tabs/windows again from before and tried with multiple twitch tabs and management view tabs and it still works. I'm not sure what the glitch was so I'll close this. Thanks, the extension is perfect
