### ISSUE TITLE
Feature request: Hide in "Following" page

### ISSUE THREAD

**Issue by notNSANE** [kwaschny/unwanted-twitch#4]
Again with a weird request - we can already hide super popular channels but I would really like if we can hide live streams on our Following page (on Overview or Channels). 

Thanks again for this great extension :)

**Comment by kwaschny** [comment]
What exactly is the use case here? You don't want to see a followed channel as long as game X is streamed?

I consider the following page for sacred. I wouldn't want my favorite streamers to be hidden, regardless of the content.
