### ISSUE TITLE
Frontpage broken

### ISSUE THREAD

**Issue by gkchesterton** [kwaschny/unwanted-twitch#40]
Hi there, it looks like a Twitch update has broken this amazing extension again. I'm running it on Edge via the Chrome store. Worked great a couple days ago, but now it doesn't block or show up on the main page at all, even with no other extensions running. Thank you.

![msedge_Hrr3mhcU3C](https://user-images.githubusercontent.com/72710301/95689759-95437680-0bd8-11eb-8661-9e3178dccecc.png)

**Comment by kwaschny** [comment]
Yep, frontpage is no longer detected properly. Affects all browsers. Trying to squeeze it in in the next few days, so it should be fixed before the upcoming weekend.
