### ISSUE TITLE
Blacklisted Channels appearing in Recommended Channels

### ISSUE THREAD

**Issue by delmain** [kwaschny/unwanted-twitch#42]
I don't have a format, so I apologize if there's information I'm leaving out.

As the title says, blacklisted channels are appearing in the Recommended Channels section of the Following page. The X appears to add them to the blacklist, and clicking it does add the user to the black list (checking via the Manage Blacklists button), but it doesn't hide the user. Multiple refreshes and hard-refreshes didn't fix the issue.

Just to check if it was an issue with the specific channel, I tried two things:

1. Viewing the category for the channel that is blacklisted. The user appears in the list for a split-second and is removed after the page finishes loading, as normal.
2. Adding a new user to the blacklist. This does not remove the user from the Recommended Channels section, but viewing the category for the new channel also shows the new channel removed after the page finishes loading.

I suspect something changed in the structure of the Recommended Channels section, but I'm not familiar with how you're currently fetching them so I don't know what info would help.

Windows 10
Firefox 82.0.1 (64-bit)

**Comment by kwaschny** [comment]
Yeah, the selector no longer matches the classes/attributes to detect and remove the nodes under "Recommended Channels". Twitch is never tired of changing that stuff.
