### ISSUE TITLE
Purple overlay when hovering on channels

### ISSUE THREAD

**Issue by Kiewan** [kwaschny/unwanted-twitch#43]
Hello,

since recently there is a purple overlay displayed, see printscreen.
using version 20.10.13
![image](https://user-images.githubusercontent.com/63482707/97821368-7786a000-1cb2-11eb-8d7d-2f01cfdf2c4a.png)

**Comment by kwaschny** [comment]
Are you using an extension that impacts CSS/styles on websites such as "Stylish" or "Stylebot"? Alternatively right-click the element and select `Inspect` (bottom item in context menu). It will open the developer toolbar that shows the styles loaded for the element. It will indicate where the excessive styling is coming from.

**Comment by alxthaman** [comment]
Got the same thing, but not always, seems like they're tweaking the design of the site.

![Sans titre](https://user-images.githubusercontent.com/22872157/98174943-f61f4f80-1ef5-11eb-9579-591b3c40c94b.png)

**Comment by kwaschny** [comment]
I noticed the X also moved to the left, so I assume they either added more nodes or changed the nesting altogether. I'm afraid I can't fix that right now. I need to see what's going on in the DOM.

**Comment by Zenzou** [comment]
Firefox 82, addon version 20.10.13
`UTTV ERROR: Could not find the expected parent node to remove item: 
Object { type: "channels", name: "BASETRADETV", category: "League of Legends", tags: (2) […], title: "🔴killin time until Minecraft contest @ 1PM PST !New", rerun: false, node: a.tw-interactive.tw-link }
common.js:229:16
`
`UTTV ERROR: Unable to remove blacklisted item in directory: 
Object { type: "channels", name: "BASETRADETV", category: "League of Legends", tags: (2) […], title: "🔴killin time until Minecraft contest @ 1PM PST !New", rerun: false, node: a.tw-interactive.tw-link }
common.js:229:16
`

**Comment by kwaschny** [comment]
Is this still an issue for anyone? I feel like this change was either never rolled out or it is caused by something different altogether.

**Comment by alxthaman** [comment]
I can say it hasn't happened to me in quite a while now.
