### ISSUE TITLE
X button to remove thumbnails on browse page no longer appearing

### ISSUE THREAD

**Issue by cogdill** [kwaschny/unwanted-twitch#44]
There was an X button on the thumbnails that allowed me to hide channels while on the browsing pages, that X button is no longer appearing. Have tried restarting/re-adding the extension.

**Comment by kwaschny** [comment]
Did you try clicking the eye symbol on the right of the "Manage Blacklist" button? Alternatively make sure the bottom checkbox on the info dialog is checked (open dialog via extension icon in your browser bar).

**Comment by cogdill** [comment]
wow did not know there was a visibility icon on that manage button, very sorry about the trouble. thank you very much! love this extension.

    On Thursday, November 26, 2020, 4:20:27 AM EST, Alex <notifications@github.com> wrote:  
 
 


Did you try clicking the eye symbol on the right of the "Manage Blacklist" button? Alternatively make sure the bottom checkbox on the info dialog is checked (open dialog via extension icon in your browser bar).
