### ISSUE TITLE
add 'comment' prompt/field to bans

### ISSUE THREAD

**Issue by KamelittaOida** [kwaschny/unwanted-twitch#45]
would be great if you could implement an optional prompt that comes up when we ban someone.
when I see the languages and the rest I don't like, it's clear why I ban, but not if I want to go through the list eventually.
Maybe I'll feel different about something down the line, and don't want to start from the start ie clear the ban list.

a on-the-fence list would be great too (default one). In other words: for there to be a perma-ban list.

**Comment by kwaschny** [comment]
How would you integrate the prompt? Wouldn't it be way too tedious to click-away the prompt everytime you add something to the blacklist, assuming that most users probably don't want to remember the reason?

There's also the storage size issue. Storing the reason (within the blacklist fragments) will exhaust the available storage even faster - though it's probably irrelevant considering that the reason will only consist of a few words and the key/empty values could be omitted in JSON.

**Comment by KamelittaOida** [comment]
>How would you integrate the prompt?

I know practically nothing about mozilla API.
I assumed it was possible to add another column (possibly with max characters or visual cut-off = ...)

>How would you integrate the prompt? Wouldn't it be way too tedious to click-away the prompt everytime you add something to the blacklist,

I wrote _optional_ above.
if turned on: prompt shows up; type phrase; [enter]
if turned on and don't want to add a reason: [Esc] or cancel

or just automatically fetch {Category/Game} and add into a column.

**Comment by KamelittaOida** [comment]
hi

>How would you integrate the prompt?

I know practically nothing about mozilla API.
I assumed it was possible to add another column (possibly with max characters or visual cut-off = ...)

>How would you integrate the prompt? Wouldn't it be way too tedious to click-away the prompt everytime you add something to the blacklist,

I wrote _optional_ above.
if turned on: prompt shows up; type phrase; [enter]
if turned on and don't want to add a reason: [Esc] or cancel

or just automatically fetch {Category/Game} and add into a column.

**Comment by kwaschny** [comment]
See [project status](https://github.com/kwaschny/unwanted-twitch#project-status).
