### ISSUE TITLE
[Option] Redirect to homepage when arriving at the page of a blocked streamer

### ISSUE THREAD

**Issue by dtSniper** [kwaschny/unwanted-twitch#48]
With the Raid/Host Features, it's possible that after lurking for quite some time you suddenly end up watching a streamer you actually blocked. 

So an Option would be good that either prevents the host/raid from happening if the target is a blocked streamer or just sends the user back to the homepage after the raid/host.

And thanks for this awesome tool

**Comment by kwaschny** [comment]
BetterTTV and FrankerFaceZ already have an option to disable automatic raids. Adding such a feature to block only specific streams seems too niche IMO. Sorry, won't do.
