### ISSUE TITLE
Request: Support for hiding tags

### ISSUE THREAD

**Issue by Dgc2002** [kwaschny/unwanted-twitch#5]
Twitch rolled out their new tagging system and I think this presents an opportunity to expand this extensions scope.  
  
For example:  
  

![image](https://user-images.githubusercontent.com/3957791/46182586-6d537580-c292-11e8-9f35-0cf5b0ba856b.png)
  
I don't want to block the "Special Events" category entirely, but I have 0 interest in streams tagged "Football".

**Comment by therealmaxmoon** [comment]
I really need this feature, too. I am watching streams with engineering tags, but there are some people who think that handcrafting crap and showing boobs has something to do with engineering.

btw. Is there a boobs blocker, which blocks those "I have not single skill, that's why I show my boobs or do ASMR"-Channels automatically?

**Comment by kwaschny** [comment]
Any thoughts about how one would mark a tag to block? Adding an "X" to the tag label will probably end up too fiddly (accidently blocking a tag instead of clicking it). Is an input field in the blacklist management fine?

**Comment by therealmaxmoon** [comment]
I think input fields in the blacklist manager, like [suggested here for channel names](https://github.com/kwaschny/unwanted-twitch/issues/7#issuecomment-425601513) would be very helpful.

**Comment by Dgc2002** [comment]
Just some ideas:  
  
You could have a button appear when you hover over a tag in the tag search dialog:  

![image](https://user-images.githubusercontent.com/3957791/46261438-18de0f00-c4b9-11e8-8893-5b4d009fd6fe.png)


You could add a small symbol to tags under streams:  
  
![image](https://user-images.githubusercontent.com/3957791/46261420-e59b8000-c4b8-11e8-9d7e-137c33710c89.png)  
  
Or something like  
  
![image](https://user-images.githubusercontent.com/3957791/46261426-ed5b2480-c4b8-11e8-9a3d-3531816eeb29.png)
  
Super rough examples but you get the idea.

**Comment by therealmaxmoon** [comment]
> ![image](https://user-images.githubusercontent.com/3957791/46261420-e59b8000-c4b8-11e8-9d7e-137c33710c89.png)

If something like this would be on the right site of the channel and game name, too, it would be just perfekt!

**Comment by Dgc2002** [comment]
> Adding an "X" to the tag label will probably end up too fiddly (accidently blocking a tag instead of clicking it).  
  
Sorry kind of glossed over that. I really think this is the most intuitive way to go about it. To address your concern maybe a modal warning saying "This will hide all streams with the tag 'tag_name', are you sure?" with "Cancel", "Yes", and "Yes, Don't show this warning again" buttons?
  
> Is an input field in the blacklist management fine?  
  
I feel like that's too hidden. Currently most of the interaction with hiding streams/categories is through the Twitch UI. I rarely think about going into the blacklist management and even less often do I actually go to it.

**Comment by kwaschny** [comment]
> [...] maybe a modal warning saying "This will hide all streams with the tag 'tag_name', are you sure?" with "Cancel", "Yes", and "Yes, Don't show this warning again" buttons?

Yes, I was already thinking about that. A simple `confirm()` on click that informs about blocking games and channels htat contain the tag.

> I feel like that's too hidden. Currently most of the interaction with hiding streams/categories is through the Twitch UI. I rarely think about going into the blacklist management and even less often do I actually go to it.

I'll add a button next to the filter dropdown on the directory page to access the management window. Eventually people will ask how to restore tags.

**Comment by kwaschny** [comment]
Implemented with: b6e509a

![preview](https://user-images.githubusercontent.com/35005943/46378102-e55ada80-c69a-11e8-8bcd-9c70f7c3c09d.jpg)
