### ISSUE TITLE
Improving "hide stream reruns" function with an extra title filter

### ISSUE THREAD

**Issue by GoldMath** [kwaschny/unwanted-twitch#50]
Hello, 

Most rerun streams don't use the Twitch "RERUN" function and straight broadcast as "LIVE" with a "RERUN:" or "[RERUN]" in title.
Could it be possible to also add a title filter of these cases when using the "hide stream reruns" function? 

Regard, thanks!

_example_
![Capture](https://user-images.githubusercontent.com/7282547/107043439-52c72a80-67c3-11eb-88f5-54c132f8a4ad.jpg)

**Comment by kwaschny** [comment]
You can do this via regular expression pattern in the 4th column of the management view. If a pattern is matched against the channel title, it will be hidden.

The pattern would be: `/RE[ -]?RUN/`
That blocks all channels with a title containing:
- RERUN
- RE RUN
- RE-RUN
