### ISSUE TITLE
Feature reqest: Remove X and add the blocking to context menu....

### ISSUE THREAD

**Issue by TeddAndersen** [kwaschny/unwanted-twitch#51]
Please remove the overlay X and add the blocking to rightclick/context menu to declutter the already cluttered twitch overlay...
As it is now, it just flotes abow the playtime and looks bad...and this function is not needed to be visible all the time ?

Maybe move it to the right side in the "tw-media-card-meta__links" field... right of the channel/streamer name field ?

Another thing... How to acces the options if you remove the extension from the addresfield? .. cant find a way to get to the settings without removing all traces of the extension and reinstall it :(

**Comment by kwaschny** [comment]
There is an 👁 eye icon on the "Manage Blacklist" button. The button is visible on frontpage (below the carousel on top) and directory pages (categories/channels) on the top right. Click the eye to toggle visibility of the `X`. You can also do it via the checkbox in the extension's popup menu. Access to the extension popup depends on the browser. It's usually a submenu where all extensions reside (Chrome uses a puzzle tile icon, Firefox uses a >> two arrows button.

![image](https://user-images.githubusercontent.com/35005943/107217637-bd1fdb00-6a0e-11eb-8c62-b6b16b76f0e4.png)
![image](https://user-images.githubusercontent.com/35005943/107217671-cb6df700-6a0e-11eb-9416-4d7886e0a1b2.png)

**Comment by TeddAndersen** [comment]
Thanks for the info and the ability to remove the X's :)

Is there an option to remove/hide the icon in the url/search field somwhere too... ? Would be nice to be able to move it to overflow as its not needed all the time....  :)

Sorry if im demanding to mutch... but got a thing about clutter in the gui of programs... like in this case a forced icon one would use maybe 1-3 times a month after the initial setup... Brings back the horror of all the rouge and useless toolbars in the web browser back in the days....(am an old fart of a sysamin...been in the game sinse middle 80's... so old :P )

**Comment by kwaschny** [comment]
> Is there an option to remove/hide the icon in the url/search field somwhere too... ?

I assume you are on Firefox? [Mozilla broke it a few months ago in version 90](https://bugzilla.mozilla.org/show_bug.cgi?id=1712556). The icon is drawn by the browser itself and I have no control over this. So you will have to wait for them to fix it. 😕

Alternatively, [there is a workaround available](https://www.reddit.com/r/FirefoxCSS/comments/ojvyee/what_changed_with_pageactionbuttons_in_firefox_90/h54aev2/), if you are up for that.

**Comment by mariogarridopt** [comment]
Maybe I'm alone in this opinion, but, **I like the icon on the URL**, it lets me know that my content is been filtered by the extension. 
Sometimes I access twitch with an account that does not have this addon and by the icon not being there it let me know that the list is not filtered.

**Comment by kwaschny** [comment]
See [project status](https://github.com/kwaschny/unwanted-twitch#project-status).
