### ISSUE TITLE
Question about changing X button position

### ISSUE THREAD

**Issue by linux858** [kwaschny/unwanted-twitch#53]
how can i move the x button showing in streamer thumbnail to the bottom right corner instead of top right corner. its overlay on the live timer for streamer

**Comment by kwaschny** [comment]
I assume you mean the "live timer" from FFZ? I guess we can detect if FFZ is used and then just offset the "X" button a few pixels to not overlap.

Something like this:
<img src="https://user-images.githubusercontent.com/35005943/113327938-e0367f00-931b-11eb-95af-36060b3cdcee.png" height="200" />

In the meantime, you can just hide the "X" button and toggle it back on as soon as you want to block something.

**Comment by kwaschny** [comment]
Integrated with bafc18159746461dd1d1943e1d7bc53c74807b94 in `21.5.21`.
