### ISSUE TITLE
Getting memory error

### ISSUE THREAD

**Issue by teodor-a** [kwaschny/unwanted-twitch#54]
Hi! I've hidden many streams using this great addon. Lately however I've been getting the following error when clicking 'x' to hide a stream:

> The storage service encountered an unexpected error.
> Please wait a few minutes, restart your browser and try again.

Is there a limit to the number of streams I can hide?

**Comment by kwaschny** [comment]
> Is there a limit to the number of streams I can hide?

Yes, the cloud storage provided by your browser has a maximum quota. It also throttles if there are too many requests. However, it should show a different/more specific error message in these cases, so I assume something else might be wrong.

Make sure to backup your current blacklist (export and save the `.json` file somewhere on your disk) and then try to switch to the local storage (disable the cloud sync in the extension's manage view). This will lift the quota and won't throttle at all. If that doesn't help, I need to investigate it using your blacklist.

**Comment by teodor-a** [comment]
Sweet, thanks a lot! With cloud storage disabled, works like a charm again.
