### ISSUE TITLE
Extension no longer works

### ISSUE THREAD

**Issue by Tacanacy** [kwaschny/unwanted-twitch#56]
The 'X' button to hide things has permanently stopped appearing, it happened a few months ago. Until then, I could just refresh the page, and the 'X' button would appear again, but this doesn't fix it anymore. 
I use Chrome version 90.0.4430.212, and I've deleted Cookies and cached images and files.

**Comment by kwaschny** [comment]
Can you post the output of the browser console please?

**How to:** Go to the Twitch website, press the `F12` key and visit the `Console` tab. Refresh the page and post the console's content. The extension logs issues starting with `UTTV`.

**Comment by Maverynthia** [comment]
Have your tried clicking on the 👁 next to Manage BLacklist? THat makes the Xs appear and disappear

**Comment by Mercurian** [comment]
A bump for this, the X has indeed vanished, now that twitch displays the time the channel has been live where it would be.

BUT, more importantly than that, and still in the same topic. Tags are not being blocked. And the following page is not being blocked. I've blocked all the languages I don't speak so I won't see them but they're still there. Same with my following page, I block a game I don't want to see and they remain.

**Comment by kwaschny** [comment]
> And the following page is not being blocked.

Are you aware of the `Also filter on the "Following" Page` setting in the management view? By default, the extension doesn't filter on "Following". This includes not attaching "X" buttons to any items there. The exception is the "Recommended" area, which is supposed to be filtered regardless.

I released a new version (`21.5.21`) yesterday, which is already available on Chrome Web Store. Make sure to (manually) update to the newest version as it sometimes takes a day or two to automatically update. As for Firefox and Edge: The update is still in (manual) review and will take a few more days to release.

**Comment by Bashur** [comment]
I use Firefox and the extension is no longer filtering out channels on my blacklist, at least not on the following page. I do have the "Also filter on the "following" page" checkmarked in settings.

**Comment by kwaschny** [comment]
> I use Firefox

The new version is still in review by the Firefox Add-ons team and not yet available. (Usually extension updates on Firefox are the fastest to be available due to automatic checks, but they recently switched UTTV to require manual review as they plan on promoting it in their blog campaign over summer. The new version should fix the issues.

If you don't want to wait, you can manually load the new version in Firefox. [Download it from Github](/kwaschny/unwanted-twitch/raw/master/publish/firefox/21.5.21.zip?raw) and install it via "..." menu in `about:addons`.

**Comment by Tacanacy** [comment]
> Have your tried clicking on the 👁 next to Manage BLacklist? THat makes the Xs appear and disappear

Thanks, that was the issue.

**Comment by kwaschny** [comment]
I will close this now as the initial case has been resolved. As for further bug reports, please update to version `21.5.22` first and then open a new issue if the problems still persist.
