### ISSUE TITLE
Can't block tags outside Browse > Categories

### ISSUE THREAD

**Issue by jbasabe** [kwaschny/unwanted-twitch#57]
The "X" button on tags only appears on the _Browse Categories_ page, but not in _Browse Live Channels_ or any game's _Live Channels_/_Videos_.
Tags under _Blacklisted Tags_ on the extension's settings are still showing.

I'm currently using version 21.3.21 of Unwanted Twitch, all other extensions are disabled, version 88.0.1 of Firefox.
![1](https://user-images.githubusercontent.com/43812128/118789680-4e67de80-b895-11eb-8fcc-8d2a5f20fbd1.PNG)
![2](https://user-images.githubusercontent.com/43812128/118789683-4f007500-b895-11eb-985c-9fa7432b0069.PNG)

**Comment by mikefirefly** [comment]
Same behaviour on Brave.
