### ISSUE TITLE
Can't Block Channels (Google Chrome)

### ISSUE THREAD

**Issue by m22b** [kwaschny/unwanted-twitch#58]
Example :
https://www.twitch.tv/directory/game/Counter-Strike%3A%20Global%20Offensive/clips?range=24hr

Push on "x" 

And nothing :( 

https://imgur.com/0qznWDP

Last version of Google Chrome...

**Comment by Osahashi** [comment]
It's not working on Firefox too. 

SirStendec from FFZ made a few Tweets on Twitter about changes Twitch made, maybe it broke the addon https://twitter.com/SirStendec/status/1394386384207687683

**Comment by kwaschny** [comment]
> maybe it broke the addon

Not just "maybe". Twitch changes markup or stylesheets and there is a very high chance UTTV no longer detects the content properly.

**Comment by kwaschny** [comment]
Fixed with 99feaa3e18021b07a7f1393d6c0e7716063e547e in `21.5.21`.
