### ISSUE TITLE
No more hiding channels on top of the home page

### ISSUE THREAD

**Issue by Hawkiinz** [kwaschny/unwanted-twitch#64]
Since today (or maybe before), Unwanted Twitch is no more hiding channels that I've selected on the top of the home page.
But it's still working if you go in a Category for example.

**Comment by Zenzou** [comment]
Can you confirm what browser and what version you have? Firefox hasn't updated to 21.6.6 yet for example.

**Comment by Hawkiinz** [comment]
Chrome 91.0.4472.101

**Comment by Zenzou** [comment]
Version of the add-on?

**Comment by Hawkiinz** [comment]
21.6.6

**Comment by kwaschny** [comment]
> no more hiding channels that I've selected on the top of the home page

Can you elaborate? WHat's the URL and can you provide a screenshot of the area you are referring to?

**Comment by Hawkiinz** [comment]
https://www.twitch.tv/
The home page

And this area :
![image](https://user-images.githubusercontent.com/45894451/121775613-164c7680-cb89-11eb-9c9b-25a5b7c8dfcb.png)

**Comment by kwaschny** [comment]
The carousel on the frontpage is not supported and has never been filtered. I am not planning to change that as it can easily break other functionality on the frontpage.
