### ISSUE TITLE
cosmetic filtering/empty space

### ISSUE THREAD

**Issue by Osahashi** [kwaschny/unwanted-twitch#65]
thanks for fixing the following page filtering, it filters now, but it seems the cosmetic filtering doesn't work, it worked in older versions before the add-on broke with the Twitch changes

it looks like that now:

![1](https://user-images.githubusercontent.com/22057956/121889738-e385b800-cd19-11eb-97db-47b1c833920d.JPG)
![2](https://user-images.githubusercontent.com/22057956/121889741-e4b6e500-cd19-11eb-9e94-382ddab3beda.JPG)

It does not work to reload and I can't fix it with uBlock0, is it a issue with your add-on? Can you do something about it?

**Comment by kwaschny** [comment]
Twitch changed the DOM in a way where where I can no longer reliably determine the topmost parent node before the full container. Assuming a fixed node could potentially result in blanking the full view once Twitch changes something up. And that's too risky IMO. Besides that, most viewports do not benefit from making room as they do not re-populate automatically.

**Comment by Osahashi** [comment]
Do you think it could be possible to "fix" that issue with an uBlock rule? You can remove the empty space, but it only works for the current page and breaks the page after new stuff, it needs to be a dynamic rule, but I do not have the knowledge to create or test something.

**Comment by kwaschny** [comment]
> Do you think it could be possible to "fix" that issue with an uBlock rule?

Probably, if there's either a lookahead or an upwards selector available.
