### ISSUE TITLE
[Feature Request] Feature to block or replace video thumbnails to avoid spoilers.

### ISSUE THREAD

**Issue by GitHubro5** [kwaschny/unwanted-twitch#66]
Hello.

Thumbnail function is intuitive and convenient, but it also has fatal problems.
One of them is as follows.

It would be very embarrassing and upsetting if a user was given a spoiler of an important game (for example, Visual Novel types) while exploring Twitch.

I hope there is a function to prevent this.

**Comment by kwaschny** [comment]
This feature already exists in [FrankerFaceZ (FFZ)](https://www.frankerfacez.com/). It will blur the thumbnails, see attached screenshot.

![image](https://user-images.githubusercontent.com/35005943/124355353-f13fa680-dc10-11eb-8fc3-1cd913b15ed5.png)

I generally won't add features that are already covered by FFZ.

**Comment by GitHubro5** [comment]
Thanks for the reply.

I tested the app you mentioned.

The function works well, but there is one problem.
It seems to work only by specifying categories.
Must be specified by user.

I basically want the ability to toggle disable/hide thumbnail of all categories without any specific category rules.

**Comment by kwaschny** [comment]
In this case you want to check out [Stylebot](https://chrome.google.com/webstore/detail/stylebot/oiaejidbmkiecgbjeifoejpgmdaleoha), an extension that allows you to apply custom CSS to any website. You can easily toggle the blur style then. This should do the trick:

```
img.tw-image[src^="https://static-cdn.jtvnw.net/previews-ttv/"],
img.tw-image[src^="https://static-cdn.jtvnw.net/cf_vods/"],
img.tw-image[src^="https://clips-media-assets2.twitch.tv/"]
{
  filter: blur(100px);
}
```

**Comment by GitHubro5** [comment]
Please understand my late reply.

I tried the way you told me.

It works well.

Thank you so much.
