### ISSUE TITLE
Latest twitch update appears to have broken 'X' showing on streams and stream hiding functionality

### ISSUE THREAD

**Issue by SneakyAzWhat** [kwaschny/unwanted-twitch#67]
1) The X is visible when browsing categories enabling the ability to hide categories but within categories I no longer show the X to be able to hide specific channels/streams

2) Channels that are on my blacklist are now appearing when browsing twitch, presumably their latest update broke some of this functionality. 

I am using firefox on windows 10.

**Comment by kwaschny** [comment]
Everything is still working for me. I wonder if that's another round of just partially rolled out changes by Twitch.

**Comment by SneakyAzWhat** [comment]
> 
> 
> Everything is still working for me. I wonder if that's another round of just partially rolled out changes by Twitch.

I don't remember the specific date this change occurred but the thumbnails when browsing within a category changed somewhat recently. Here is a screenshot for reference: https://i.imgur.com/WAY9htu.png

**Comment by kwaschny** [comment]
Yep, that's a feature preview you are on. Most of us are still on the old views. Unfortunately I cannot fix that as long as it is not rolled out to everyone.

**Comment by CinYog** [comment]
> Yep, that's a feature preview you are on. Most of us are still on the old views. Unfortunately I cannot fix that as long as it is not rolled out to everyone.

How does one get back to the "old view".
None of the "tag" blocks are being blocked and there is no X to any tag now anymore. 

Thanks in advance.

**Comment by kwaschny** [comment]
> None of the "tag" blocks are being blocked and there is no X to any tag now anymore.

That's a fresh change even I get, so expect a fix for this soon. Twitch's "patch day" seems to be Tuesday.

> How does one get back to the "old view".

You probably can't. Try logging out or open an incognito tab to check, if the canary version is attached to your account. If you are referring to the tags no longer working, that broke for everyone.

**Comment by CinYog** [comment]
> > None of the "tag" blocks are being blocked and there is no X to any tag now anymore.
> 
> That's a fresh change even I get, so expect a fix for this soon. Twitch's "patch day" seems to be Tuesday.
> 
> > How does one get back to the "old view".
> 
> You probably can't. Try logging out or open an incognito tab to check if the canary version is attached to your account. If you are referring to the tags no longer working, that broke for everyone.

Okay, understood.  Thanks.

Incognito doesn't work either.

**Comment by CinYog** [comment]
You are a legend, it's working. 
Thank you.
