### ISSUE TITLE
How to block channels, which are currently watched?

### ISSUE THREAD

**Issue by therealmaxmoon** [kwaschny/unwanted-twitch#7]
I am only able to block channels if I can see the thumbnail, but how to do it, if I get a link to a channel and I really want to block it?

**Comment by kwaschny** [comment]
This approach seems a little odd to me. I'd rather not add a button to the channel page just for the sake of blocking. Does manually blocking by name (game/channel) in the blacklist management sound good to you?

**Comment by therealmaxmoon** [comment]
Adding it by hand would be very nice.

**Comment by kwaschny** [comment]
Implemented with: cd02d8e
