### ISSUE TITLE
[Feature suggestion] Use as a whitelist

### ISSUE THREAD

**Issue by KlausEverWalkingDev** [kwaschny/unwanted-twitch#74]
As the majority of the Twitch content (such as gaming categories, other languages except Portuguese and English) doesn't get my attention, it would be very useful if we could reverse how this extension works, changing it from a blacklist to a whitelist. So we could only cherry-pick categories, channels and tags.

**Comment by kwaschny** [comment]
That's not realizable with how the extension works in general. [Quoting from the README](https://github.com/kwaschny/unwanted-twitch#how-it-works):

> The extension is loaded after the requested twitch.tv page is fully served and completely relies on the present DOM.

You are probably better off with a standalone alternative UI for Twitch such as [Livestreamer](https://github.com/streamlink/streamlink-twitch-gui), where the app only queries desired data.
