### ISSUE TITLE
Blank export while loading

### ISSUE THREAD

**Issue by djcline23** [kwaschny/unwanted-twitch#76]
I have a big blacklist that takes a while to load when I use Manage Blacklist. Today I hit export to do a backup before all the blacklisted items appeared on the management screen and the export was blank and the blacklist was then empty. So it seems the loading needs to complete for a successful export? In which case don't enable export button until loading is complete?

**Comment by kwaschny** [comment]
Yes, the save and export action store whatever is present in the view. If the blacklist takes too long or fails to load for whatever reason, you can end up saving/exporting an empty list.

I guess I should disable the action buttons before the callback returns successfully.
