### ISSUE TITLE
name with _

### ISSUE THREAD

**Issue by SatisfactoryBug** [kwaschny/unwanted-twitch#77]
i think it don't work if it have a two _ _ like this name_name_name

**Comment by kwaschny** [comment]
**What** does not work? I just tested `The_Happy_Hob` and it works fine.

The only reason it might not match a channel in the directory is a mismatch between display name and channel name. I remember there was a channel in the past (somnething CS:GO related, I think) that had two different spellings. So when the detection grabs the wrong identifier, it is never matched.

Anyway, you will need to provide some more information.

**Comment by kwaschny** [comment]
Closing this as no information have been provided.

**Comment by SatisfactoryBug** [comment]
yeah sorry about that as PC was down...., you right it strange as it working now which is odd but than for the update
