### ISSUE TITLE
viewers also watch list showing blocked users

### ISSUE THREAD

**Issue by portno12** [kwaschny/unwanted-twitch#78]
when on a channel on the sidebar with followed/recommended/etc the section labelled "X viewers also watch" still shows users who have been blocked by this extension. i double checked the spelling of the username and verified the list is being applied. this behavior has occurred with two different users so far across multiple channels.

**Comment by kwaschny** [comment]
>the section labelled "X viewers also watch"

Interesting. I've never seen this section and it doesn't show up on any of my test accounts. It's either an experimental feature or simply based on your browsing/viewing behavior.

It doesn't work because there are no definitions for detection in the current extension. I'm afraid there's nothing I can do about it for now.

**Comment by portno12** [comment]
if there is any info i can provide let me know and i can try to help. sadly i am not knowledgeable in extension development to directly do a pr for this.

**Comment by kwaschny** [comment]
I assume the issue has resolved itself.

**Comment by portno12** [comment]
it does not seem to have resolved itself. i was waiting to see what other info i could provide to you if any to get it resolved but did not hear back yet

**Comment by kwaschny** [comment]
I have not seen this area on the sidebar yet. I need to see the DOM to write selectors for it. Yet I would still not be able to actually test this properly. 😕

I can offer you a build you add manually to your browser that shows debug info (in console). Testing would be up to you then. First step would be posting the DOM of your sidebar (redact any info you feel uncomfortable sharing). Let me know, if you are interested.

**Comment by portno12** [comment]
if you want to reopen this i can get the info but might not be for a couple days or so.
