### ISSUE TITLE
Blacklisted channels who aren't blacklisted.

### ISSUE THREAD

**Issue by Maelep** [kwaschny/unwanted-twitch#79]
I'm following [twitch.tv/Katrine](https://www.twitch.tv/katrine) for months without problems but I just saw today that she was online while navigating in ASMR category but she's isn't showed in my followed channels.

- Disabling the extension make her appears. Enabling it again make her disappear.
- The ASMR category isn't blacklisted.
- Katrine isn't blacklisted.
- Katrine was live (I messaged her and she answered me)
- Katrine appears in the list of ASMR streamers.

What's happening?

**Comment by kwaschny** [comment]
Broadcasting a rerun maybe? There is an option to hide reruns, regardless of the channel. Also, do you have any tags in the blacklist that the channel might have hit at that time?

![image](https://user-images.githubusercontent.com/35005943/156629817-a55122bc-b2c7-4b7f-8f2b-fba721ea3395.png)

Filtering works fine on my end so I don't really have an explanation other than being it a rerun.

**Comment by Maelep** [comment]
I thought it was rerun, that's why I asked if it was live and she answered me (orally, from her stream).

I don't know from where it comes 😕

Does blacklisting a category could backlist the streamer?

**Comment by kwaschny** [comment]
Not reproducible. Case closed for now.
