### ISSUE TITLE
Blacklisting streams broke completely

### ISSUE THREAD

**Issue by meatball4u2** [kwaschny/unwanted-twitch#84]
Hello, I just found out that my whole blacklist stopped working. I'm using the latest version of Firefox. Now, even when I click the "x" to remove the stream it doesn't stay gone. Certain streams show up briefly then disappear (like they used to), but they're not the one's I've blocked. Did Twitch change something to break this?

**Comment by kwaschny** [comment]
I just checked on Firefox 101.0.1 and it seems fine to me. On which URL does it happen (check browser address bar)? Do the items you block via X button appear in the list when you go to the management view? Press `F12` to open the browser console (might need to switch tabs there) and checkif there are any UTTV related errors or warnings (they are prefixed, you may ignore other warnings).

**Comment by JoseSM** [comment]
I can confirm I have the same problem, I can see all the channels that are on my blacklist. However if I click on the X button then it hides the channel and it stay hidden when I reload. Taking a look the behavior of the blacklist at this point may help you.
For example I have this channels:

![imagen](https://user-images.githubusercontent.com/905016/173931014-e472cd0b-0439-4d74-a7d5-7eb2f07cd926.png)

![imagen](https://user-images.githubusercontent.com/905016/173932293-ae22dc36-e860-4411-aca5-8b8b58cada6a.png)

This way it doesn't work but when I click on the X buttom it add this to the blacklist and it works:

![imagen](https://user-images.githubusercontent.com/905016/173931144-b337dd2e-2367-478f-988a-4b8cf306a411.png)

![imagen](https://user-images.githubusercontent.com/905016/173932351-17f110b3-ee6f-4212-a846-f2fd509c15b0.png)

This is the title of the stream + the name of the channel and then it hides it properly.

The URL where I tried this is https://www.twitch.tv/directory/following
I'm using Firefox 101.0.1 (64-bit)
No UTTV errors or warnings on the console.

**Comment by kwaschny** [comment]
> This is the title of the current stream + the name of the channel and then it hides it properly.

I see. Yes, Twitch changed nodes and now the channel name detection also grabs unrelated text, in this case the title.
