### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by gozaru000** [kwaschny/unwanted-twitch#85]
The old black list is not valid
When adding a new blacklist, it seems that the title is also included as part of the name

**Comment by kwaschny** [comment]
Duplicate of #84 ? Are you on the newest version `22.06.15` that was just released yesterday for Chrome? Firefox and Edge updates are still being reviewed.

**Comment by gozaru000** [comment]
I'm using firefox
It looks like the problem has been solved 
Thank you for your maintenance
