### ISSUE TITLE
Extension not blacklisting on the site: https://www.twitch.tv/directory/*

### ISSUE THREAD

**Issue by UltimoTheUltimate** [kwaschny/unwanted-twitch#87]
The extension isn't attempting to blacklist the channels on e.g. https://www.twitch.tv/directory/irl . Also the added buttons to hide categories and channels aren't visible. Likely caused by a twitch update. (hope it's not because i'm a version behind due to chrome web store)

**Comment by kwaschny** [comment]
This view (grouping of multiple categories) has never been supported. Especially the "Esports" one is pretty exotic. As long as Twitch frontend devs don't bother making unified channel tiles, this will just increase (my) maintenance effort. So I'm not exactly keen on adding support for even more views.

I will treat this as a feature request. Knowing that Twitch is currently testing a complete overhaul of the directory browsing system, I'm not sure if this is the best timing to work on this.
