### ISSUE TITLE
Sync filtering of "unwanted twitch" with "FrankerFaceZ Deck Addon".

### ISSUE THREAD

**Issue by Fujosej** [kwaschny/unwanted-twitch#88]
Hi , love this extension , very easy to use and works as intended. 
i have a suggestion if it's even a possibility to implement it. 

So i am using frankerfacez's Deck addon to improve native sidebar that twitch has , with deck you can impove sidebar and add to it extra filtering and make it more fitting to your needs. for example mine is set up in this way , so i can mix and match , remove or add almost anything to it , with some limitations of course. 
![image](https://user-images.githubusercontent.com/37980944/179499316-3f7a84e2-9b1c-4696-bcdb-3216395d7c1e.png)
So in order to enable this sidebar feature you have to tick this box in a Deck addon. Any Deck can become a sidebar.
![image](https://user-images.githubusercontent.com/37980944/179504394-06cc5949-5c4c-49c4-b269-87b163551f1a.png)

So my question is, with "unwanted" extension and deck/sidebar both enabled , when you filter something out with "unwanted" extension, it's still shows up in deck , so they don't really sync with each other, and that's kinda logical why it happens, but i do wonder if there is a way to make them sync with each other. It's probably very hard to implement , sorry if this sounds really out there, i just wanted to know if there is a way to do this.

**Comment by kwaschny** [comment]
See [project status](https://github.com/kwaschny/unwanted-twitch#project-status).
