### ISSUE TITLE
Blacklisted titles does not make the stream in the sidebar disappear

### ISSUE THREAD

**Issue by Chat-mots** [kwaschny/unwanted-twitch#92]
**Expected Behavior** : when a stream is blacklisted because of his title, the stream should disappear from the website and the sidebar.

**Actual behavior** : when a stream is blacklisted because of his title, the stream is, as expected, removed from the website. But remains in the sidebar.

**Comment by kwaschny** [comment]
The extension can only filter information that are present in the view. The sidebar only exposes channel name and category. The title is not available and thus cannot be evaluated. Filtering via title is not possible in this case.
