### ISSUE TITLE
'x' to add stream to block list has disappeared on the latest version of Firefox

### ISSUE THREAD

**Issue by meatball4u2** [kwaschny/unwanted-twitch#95]
Title

Noticed this about 2-3 days ago

**Comment by kwaschny** [comment]
Still seems fine here. Are all of your views affected? Can you share a screenshot? Did you notice any changes to the layout or new UI features? Because I assume you might have been picked as guina pig for an upcoming change, see the [current canary build](https://canary.twitch.tv/).

**Comment by meatball4u2** [comment]
All views affected. Haven't noticed any layout or UI changes. Here's a screenshot
![unwantedtwitchscreen](https://user-images.githubusercontent.com/107583184/195707332-68950841-188a-411e-a2ca-347c1ed7348e.png)

**Comment by kwaschny** [comment]
This is how the site looks to me right now:

![image](https://user-images.githubusercontent.com/35005943/195711852-a605e8d4-0051-4e13-98ac-1b991a0a9a6e.png)

Unless you are using some kind of style customization, at least the style of search input and tag buttons has changed. And this probably means changes to the DOM that break the detection logic on where to place the X buttons.

Unfortunately there's nothing I can do right now. Maybe the changes will be deployed to everyone some day, maybe not. The FFZ extension has an override feature to disable these experiments, but don't ask me which of these experiments is responsible for this.

**Comment by meatball4u2** [comment]
Gotchya. I'll have to live with it for now. Appreciate the help.

**Comment by kwaschny** [comment]
Probably not applicable in your case, but since I had a few people falling for this:

![image](https://user-images.githubusercontent.com/35005943/199846024-a377b1bd-3c7e-4e4a-9a0a-8ea6e2262b2f.png)

Make sure you didn't accidently toggle the visibility option.

**Comment by meatball4u2** [comment]
Heyyy, that did the trick! 

Thanks!
