### ISSUE TITLE
Lists got cleared.

### ISSUE THREAD

**Issue by DauwJonas** [kwaschny/unwanted-twitch#97]
All the lists were cleared at some point, I didn’t do it. I had over 800 Channels Blacklisted. I checked on the settings page because on Twitch my recommendations looked polluted. I guess I know now why.

* Is there anyway to get it back?
* And why did this happen?

I tried to get the sync data with
```js
chrome.storage.sync.get(null, function (result) {
    console.log(result);
});
```
But it seems to have overwritten the sync or it was also lost.
I hope you have a way to get it back, like maybe you have a backup system that saves to Google Drive or saves a backup to sync 1/month and never changes that and only remove it when there are enough others?

Report bugs Questions:
* What browser and what version of it are you using?
**Chrome**
* What version of Unwanted Twitch are you using?
**22.8.14**
* Are you using other extensions that might affect the Twitch website?
**7TV, BetterTTV, Twitch Adblock, uBlock Origin, I don't care about cookies.**
* Does disabling all the other extensions (except Unwanted Twitch) help with the problem?
**Well, the listed is cleared so I don’t think it matters anymore, but disabling 7TV & BetterTTV doesn't bring the list back, so does restarting Chrome.**
* What are the steps to reproduce the problem?
**I don't know.**
* If applicable: Can you show a screenshot of the issue?
  * Befor: ![image](https://user-images.githubusercontent.com/43506590/198408027-e914029b-63fd-44ac-8006-9142061d5c46.png)
  * Now: ![image](https://user-images.githubusercontent.com/43506590/198407916-387445ef-8b0f-4689-85c5-de2c6f397895.png)
  **I think these are all new once as I added a lot in the last days.**
* Advanced users: Share the console messages and stacktrace. **How to**: Open the developer toolbar pressing `F12` and keep it open. Reload the page you are having the issue on by pressing `F5`. Switch to the `Console` tab in the developer toolbar. Check for warnings/errors starting with `UTTV:` (consider using the filter), click on them to expand the stacktrace. Include a screenshot of it in your report.
**There are no errors from UTTV, on Twitch and in the (chrome-extension) settings page.**

**Comment by kwaschny** [comment]
Thank your for the detailed report. Did you ever change the storage mode (checkbox at the top right in the settings view)? By default, the blacklist is stored via cloud (`chrome.storage.sync`) and thus the data is stored on Google's own storage service for Chrome that is **not** related to user facing services such as Google Drive. The alternative storage mode `chrome.storage.local` is stored on your local computer's disk. In both cases, all data is cleared when the extension is uninstalled. Changing privacy settings or clearing synchronized data in your Google account might also have impact, but I am not 100% sure.

If you never uninstalled and didn't fiddle with your Google account privacy, the only thing left is a network related problem, such as a failed retrieval of your blacklist that made you overwrite your list with a new list of only a few new items added. I implemented a fallback system for cases where the storage service is not responding properly (or quota being exceeded), but I am not certain if this helps in every single circumstance.

> I hope you have a way to get it back, like maybe you have a backup system that saves to Google Drive or saves a backup to sync 1/month and never changes that and only remove it when there are enough others?

No such thing. I am not touching any user data ever. It's either on your disk or on the Google cloud. There is an export/import to save your blacklist as `.json` file, so you can do manual backups. If you never did a backup, I'm afraid you probably lost these 800+ channels. 😕

This is not the first time a user reported data loss. However, as long as there is no way to reproduce the data loss, I can only advise everyone to make regular backups. Never trust software written by humans.

**Comment by kwaschny** [comment]
I'm not trusting Twitch on the "Not Interested" feature at all. They could have implemented a proper filter, but they chose the "we want people to funnel into hyped content" path. A user suggested using their requests to maintain the blacklist in #75, but that doesn't cover channels/tags at all. Would have been nice to have a solution that doesn't require traversing the DOM, but oh well.

> (Idk if I should close this as data los might keep happening?)

Hopefully not though. I've been using my own extension for over 4 years now and I never had trouble with data loss. If you can find a way to break it and make it clear/overwrite the storage again, I would be glad to fix this.

**Comment by kwaschny** [comment]
I changed the default storage mode in 9ae3ec830b85312ddb7283fc29e5343114f4cd0d. This will hopefully reduce the likeliness of data loss as most users probably won't need the syncing feature anyway.

Closed for now. Feel free to reopen in case you find a way to reproduce the data loss.
