### ISSUE TITLE
Darktheme.

### ISSUE THREAD

**Issue by DauwJonas** [kwaschny/unwanted-twitch#98]
I would like to have a dark theme, if you want I could make it. I assume just a CSS file would be good?
(Proof that I can do it: [GitHub.io](https://dauwjonas.github.io/), [GitHub.com](https://github.com/DauwJonas/DauwJonas.github.io))

**Comment by kwaschny** [comment]
You mean for the blacklist/settings tab and the popup? I guess so. You can easily detect the user's preferences using [`@media (prefers-dark-interface)`](https://caniuse.com/?search=prefers-color-scheme) and then set the colors accordingly. Maybe refactor the colors into `:root` variables in `[common.css](https://github.com/kwaschny/unwanted-twitch/blob/master/styles/common.css)` altogether?

Sure, give it a go. 🙂

**Comment by kwaschny** [comment]
a084e37f5010a9a526971e4095cf904572fb0b2c looks good. Thank you for your contribution! ❤️

It will be part of the upcoming update.
